name: PD-MDS-Lab

on:
  push:
    paths:
      - 'app/**'
      - 'model/**'
      - '.github/workflows/**'
      - 'requirements.txt'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dataset:
          - app/data/titanic_test_base.csv
          - app/data/titanic_test_future.csv

    env:
      MODEL_PATH: model/logistic_titanic_pipeline.pkl
      TEST_DATA_PATH: ${{ matrix.dataset }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest -q app

