name: PD-MDS-Lab

on:
  push:
    paths:
      - 'app/**'
      - 'model/**'
      - 'requirements.txt'
      - '.github/workflows/producto-datos-lab.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Verificación rápida (opcional): ¿pytest está instalado?
          python - <<'PY'
          import importlib.util as i
          print("pytest installed?", bool(i.find_spec("pytest")))
          PY

      - name: Run tests
        working-directory: app
        run: python -m pytest -q
